# Generated by Django 4.0.5 on 2022-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailywage',
            constraint=models.UniqueConstraint(fields=('courier', 'date'), name='unique_courier_and_date'),
        ),
    ]
