# Generated by Django 4.0.5 on 2022-06-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages_manager', '0002_dailywage_unique_courier_and_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weeklywage',
            constraint=models.UniqueConstraint(fields=('courier', 'saturday_date'), name='unique_courier_and_saturday_date'),
        ),
    ]
